package it.gov.pagopa.noticenumber.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum AppErrorCodeMessageEnum {
    // --- Internal logic errors ---
    GENERIC_ERROR(1000, "Generic error", "Error while generating IUV. {0}", HttpStatus.INTERNAL_SERVER_ERROR),
    VALIDATION_ERROR(1001, "Validation error", "Error while validating IUV generation request. {0}", HttpStatus.BAD_REQUEST),
    GENERATION_MAX_RETRIES_REACHED(1101, "Generation error", "Error while generating IUV. Reached the maximum number of internal automatic attempts [{0}] to generate a unique IUV for creditor institution [{1}]. Please, try again later.", HttpStatus.INTERNAL_SERVER_ERROR),
    GENERATION_AUXDIGIT_ALGORITHM_INVALID_PATTERN(1102, "Generation error", "Error while generating IUV. The IUV code's section generated by timestamp in milliseconds is not correctly composited of 13 digits.", HttpStatus.INTERNAL_SERVER_ERROR),
    ;

    private final Integer code;
    private final String title;
    private final String detail;
    private final HttpStatusCode status;

    AppErrorCodeMessageEnum(Integer code, String title, String detail, HttpStatus status) {
        this.code = code;
        this.title = title;
        this.detail = detail;
        this.status = status;
    }
}
